sonar.projectKey=FedericoSib_ISPW-PROJECT-SOLO
sonar.organization=federicosib
sonar.sources=src
sonar.tests=test
sonar.java.binaries=out/production
sonar.java.libraries=lib/*.jar
sonar.coverage.jacoco.xmlReportPaths=jacoco.xml
sonar.cpd.exclusions=**/*.java
sonar.coverage.exclusions=**/*.java
sonar.exclusions=**/*.css
sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S106
sonar.issue.ignore.multicriteria.e1.resourceKey=**/cli/**
sonar.issue.ignore.multicriteria.e2.ruleKey=java:S106
sonar.issue.ignore.multicriteria.e2.resourceKey=**/MainApp.java
sonar.issue.ignore.multicriteria.e3.ruleKey=java:S6548
sonar.issue.ignore.multicriteria.e3.resourceKey=**/Sessione.java