sonar.projectKey=FedericoSib_ISPW-PROJECT-SOLO
sonar.organization=federicosib
sonar.sources=src
sonar.tests=test
sonar.java.binaries=out/production/Progetto ISPW
sonar.java.libraries=lib/*.jar
sonar.coverage.jacoco.xmlReportPaths=jacoco.xml
sonar.exclusions=**/*.css
