sonar.projectKey=FedericoSib_ISPW-PROJECT-SOLO
sonar.organization=federicosib
sonar.sources=src
sonar.tests=test
sonar.java.binaries=out/production
sonar.java.libraries=lib/*.jar
sonar.coverage.jacoco.xmlReportPaths=jacoco.xml
sonar.exclusions=**/*.css
sonar.coverage.exclusions=\
  src/view/**,\
  src/model/dao/*DAOFile.java,\
  src/util/AlertManager.java,\
  src/bean/UtenteBean.java